# Generated by Django 5.2.11 on 2026-03-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontypemodel',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='cover',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='exercises/'),
        ),
        migrations.AlterField(
            model_name='trainermodel',
            name='photo',
            field=models.ImageField(upload_to='trainers/'),
        ),
    ]
