# Generated by Django 5.2.11 on 2026-03-15 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_subscriptiontypemodel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciseinstructionmodel',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
