# Generated by Django 5.2.11 on 2026-04-01 01:05

from django.db import migrations


def add_event_types(apps, schema_editor):
    EventTypeModel = apps.get_model('api', 'EventTypeModel')
    event_types = [
        'PAGE_VIEW',
        'EXERCISE_CLICK',
        'SUBSCRIPTION_CLICK',
        'PAYMENT_METHOD_SELECT',
        'USER_PROFILE_VIEW',
        'VIDEO_PLAY',
        'SUPPORT_CLICK',
    ]
    for name in event_types:
        EventTypeModel.objects.get_or_create(name=name)


def remove_event_types(apps, schema_editor):
    EventTypeModel = apps.get_model('api', 'EventTypeModel')
    event_types = [
        'PAGE_VIEW',
        'EXERCISE_CLICK',
        'SUBSCRIPTION_CLICK',
        'PAYMENT_METHOD_SELECT',
        'USER_PROFILE_VIEW',
        'VIDEO_PLAY',
        'SUPPORT_CLICK',
    ]
    EventTypeModel.objects.filter(name__in=event_types).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_exerciseinstructionmodel_description'),
    ]

    operations = [
        migrations.RunPython(add_event_types, remove_event_types),
    ]
