# Generated by Django 5.2.11 on 2026-04-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20260401_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinstructionmodel',
            name='type',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'All')], max_length=2),
        ),
    ]
