import unittest
import json
from telegram.TelegramValidation import TelegramValidation

class TestTelegramValidation(unittest.TestCase):
    def setUp(self):
        self.token = "123456789:ABCDEFG"
        self.validator = TelegramValidation(self.token)

    def test_validate_init_data_success(self):
        # Data generated by generate_test_data.py
        init_data = "auth_date=1710000000&chat_instance=456&chat_type=sender&signature=some_signature&user=%7B%22id%22%3A123%2C%22first_name%22%3A%22Test%22%2C%22last_name%22%3A%22User%22%2C%22username%22%3A%22testuser%22%2C%22language_code%22%3A%22en%22%2C%22is_premium%22%3Atrue%2C%22photo_url%22%3A%22http%3A//example.com%22%7D&hash=65c84fd2c1b78b9eb9556f1c143b485aa910ef70902d4e8bc20f37d423e5990d"
        
        user = self.validator.validate_init_data(init_data)
        
        self.assertIsNotNone(user)
        self.assertEqual(user["id"], 123)
        self.assertEqual(user["username"], "testuser")
        self.assertTrue(user["is_premium"])

    def test_validate_init_data_invalid_hash(self):
        # Changed one character in hash
        init_data = "auth_date=1710000000&chat_instance=456&chat_type=sender&signature=some_signature&user=%7B%22id%22%3A123%2C%22first_name%22%3A%22Test%22%2C%22last_name%22%3A%22User%22%2C%22username%22%3A%22testuser%22%2C%22language_code%22%3A%22en%22%2C%22is_premium%22%3Atrue%2C%22photo_url%22%3A%22http%3A//example.com%22%7D&hash=f5c84fd2c1b78b9eb9556f1c143b485aa910ef70902d4e8bc20f37d423e5990d"
        
        user = self.validator.validate_init_data(init_data)
        
        self.assertIsNone(user)

    def test_validate_init_data_invalid_json_user(self):
        # user field is not a valid JSON
        init_data = "auth_date=1710000000&chat_instance=456&chat_type=sender&signature=some_signature&user=not_a_json&hash=any_hash"
        
        user = self.validator.validate_init_data(init_data)
        self.assertIsNone(user)

    def test_validate_init_data_missing_fields(self):
        init_data = "auth_date=1710000000&hash=some_hash"
        user = self.validator.validate_init_data(init_data)
        self.assertIsNone(user)

    def test_validate_init_data_double_unquote_success(self):
        # Case where user field is double encoded within init_data
        user_json = '{"id":123,"first_name":"Test"}'
        from urllib.parse import quote
        encoded_user = quote(user_json) # Standard encoding for query param
        
        data_to_sign = {
            "auth_date": "1710000000",
            "chat_instance": "456",
            "chat_type": "sender",
            "signature": "some_signature",
            "user": user_json
        }
        import hmac
        import hashlib
        sorted_items = sorted(data_to_sign.items())
        init_data_string = "\n".join(f"{k}={v}" for k, v in sorted_items)
        secret_key = hmac.new("WebAppData".encode(), self.token.encode(), hashlib.sha256).digest()
        hash_val = hmac.new(secret_key, init_data_string.encode(), hashlib.sha256).hexdigest()
        
        # Now construct init_data. If the whole thing is then encoded again by the transport,
        # our validator should handle it.
        init_data = f"auth_date=1710000000&chat_instance=456&chat_type=sender&signature=some_signature&user={encoded_user}&hash={hash_val}"
        double_encoded_init_data = quote(init_data)
        
        user = self.validator.validate_init_data(double_encoded_init_data)
        self.assertIsNotNone(user)
        self.assertEqual(user["id"], 123)
